#+title: Comuptational Physics
#+author: 凉凉
* About
This is the Final Project of UCAS 2024 Computational Physics.
Within this repo, there is the Monte Carlo Simulation and
Modular Dynamics Simulatioin program written in Common Lisp
via CLOS.

This package is well self documentated. Please refer the code
or the =package.lisp= for documentation, the README may not be
updated frequently. 

Since this package is written in a hurry, the documentation
and the demo code may not so adequate. 

* Example
You could try the following code to start a MC simulation:

#+begin_src lisp
  (in-package :com-phy)
  (let ((system (make-instance '2d-lj-period-mc-acc
                               :temperature 0.728
                               :density     0.8442
                               :N           100
                               :scheme      :grided
                               :step-size   0.05)))  ; dt for MD
    (run-simulation system 1000
                    :plot-config-every  100
                    :plot-collect-every 100)
    (save-system system save-path))
#+end_src

and continue from the saved simulation:

#+begin_src lisp
  (in-package :com-phy)
  (let ((system (load-system save-path)))
    (run-simulation system 1000
                    :plot-config-every  100
                    :plot-collect-every 100)
    (save-system system save-path))
#+end_src

It is, I think, accecptable fast. For system with ~N = 400~ and simulate
with 1000000 steps on my MacBook Air M1 with 6 lparallel worker, it
would cost around 16 minutes. 

* License
#+begin_quote
           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                   Version 2, December 2004
 
Copyright (C) 2024 凉凉 <https://github.com/li-yiyang>

Everyone is permitted to copy and distribute verbatim or modified
copies of this license document, and changing it is allowed as long
as the name is changed.
 
           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

 0. You just DO WHAT THE FUCK YOU WANT TO.
#+end_quote
